export const baseExerciseCatalog = [
  { name: 'Supino Reto com Barra', muscle_group: 'Peito' },
  { name: 'Supino Inclinado com Halteres', muscle_group: 'Peito' },
  { name: 'Crucifixo com Halteres', muscle_group: 'Peito' },
  { name: 'Crossover na Polia', muscle_group: 'Peito' },
  { name: 'Puxada Frontal', muscle_group: 'Costas' },
  { name: 'Remada Curvada com Barra', muscle_group: 'Costas' },
  { name: 'Remada Baixa', muscle_group: 'Costas' },
  { name: 'Barra Fixa', muscle_group: 'Costas' },
  { name: 'Agachamento Livre', muscle_group: 'Pernas' },
  { name: 'Leg Press 45º', muscle_group: 'Pernas' },
  { name: 'Cadeira Extensora', muscle_group: 'Pernas' },
  { name: 'Cadeira Flexora', muscle_group: 'Pernas' },
  { name: 'Stiff com Barra', muscle_group: 'Pernas' },
  { name: 'Elevação Pélvica', muscle_group: 'Pernas' },
  { name: 'Desenvolvimento com Halteres', muscle_group: 'Ombros' },
  { name: 'Elevação Lateral', muscle_group: 'Ombros' },
  { name: 'Crucifixo Invertido', muscle_group: 'Ombros' },
  { name: 'Rosca Direta com Barra', muscle_group: 'Bíceps' },
  { name: 'Rosca Martelo', muscle_group: 'Bíceps' },
  { name: 'Tríceps na Polia com Corda', muscle_group: 'Tríceps' },
  { name: 'Tríceps Testa', muscle_group: 'Tríceps' },
  { name: 'Abdominal Supra', muscle_group: 'Abdômen' },
  { name: 'Prancha', muscle_group: 'Abdômen' },
  { name: 'Panturrilha em Pé', muscle_group: 'Panturrilhas' },
] as const